name: 签到
on:
  workflow_dispatch:
  schedule:
    - cron: '10 17 * * *'
permissions:
  contents: read
  actions: write
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
      - name: 创建 Node 环境
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: 缓存依赖
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ./api/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: 安装依赖
        run: npm run install
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      - name: 执行签到
        run: npm run main
        env:
          USERINFO: ${{ secrets.USERINFO }}
          PAT: ${{ secrets.PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
